# Get the latest r-base image from Docker Hub
FROM r-base:4.5.0

# Install the required system dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        libcurl4-openssl-dev libssl-dev libfontconfig1-dev libxml2-dev \
        libharfbuzz-dev libfribidi-dev libfreetype6-dev libpng-dev \
        libtiff5-dev libjpeg-dev libcairo2-dev libgsl-dev libfftw3-dev \
        libv8-dev libgmp3-dev libudunits2-dev libmpfr-dev libgdal-dev cmake \
        python3 python3-pip \
    && rm -rf /var/lib/apt/lists/*

# Set the working directory
WORKDIR /home/

# Install the required R packages, we need to specify the repository since otherwise we will be prompted to select a CRAN mirror
# RUN R -e "install.packages('pacman', repos='http://cran.rstudio.com/')"
COPY ./source/install_packages.r source/
RUN Rscript source/install_packages.r

# Install the required Python packages
COPY ./source/requirements.txt source/
RUN pip3 install --no-cache-dir --break-system-packages -r source/requirements.txt